#ifndef CONSTANT_H
#define CONSTANT_H

#define YAW_SPEED_TO_CHASSIS_CH2 = 0.14090909f;
#define YAW_ANGLE_RATIO = 27.0f;
#define YAW_LEFT_BOUND_REAL_ANGLE = 65.0f;
#define YAW_RIGHT_BOUND_REAL_ANGLE = -65.0f;
#define YAW_LEFT_BOUND = 1755.0f;
#define YAW_RIGHT_BOUND = -1755.0f;
#define PITCH_ANGLE_RATIO = 19.0f;
#define PITCH_UPPER_BOUND_REAL_ANGLE = 45.0f;
#define PITCH_UPPER_BOUND = 855.0f;
#define GYRO_ANGLE_RATIO = 10.0f;

#endif

